### ISSUE TITLE
[Bug]: pypi release 0.2.0 doesn't match GitHub release

### ISSUE THREAD

**Issue by mwolinska** [CederGroupHub/chgnet#125]
### Version

v0.2.0

### Which OS(es) are you using?

- [X] MacOS
- [ ] Windows
- [X] Linux

### What happened?

1. I have previously used version 0.2.0 for my project, but when recreating an environment and installing the version CrystalGraphConverter.forward() method no longer took the "on_isolated_atoms" argument.  I saw that this was an update  in version 0.2.1. 

I checked the pypi distribution files and the chgnet-0.2.0-cp39-cp39-macosx_10_9_x86_64.whl and 
chgnet-0.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl versions contained code consistent with the 0.2.1 release. 

I noticed that the pypi distribution files were updated the day before the 0.2.1 release, so I suspect the 0.2.0 release was overwritten. 
<img width="523" alt="image" src="https://github.com/CederGroupHub/chgnet/assets/101104091/e969274a-7507-4b68-90f8-5fbfb5ff42cd">

2. Proposed resolution: republish version 0.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
If you want to keep using CHGNet v0.2.0 version, you can install the latest release by `pip install chgnet`,
And access the 0.2.0 version model by `chgnet = CHGNet.load('0.2.0')`
The latest release should support the [on_isolated_atoms key](https://github.com/CederGroupHub/chgnet/blob/3f1c72210a91e9ac1ae1b3f3805e598db404c6df/chgnet/graph/converter.py#L39)

There have been many small improvements and bug fixes since 0.2.0 release, I would recommend using the most recent release even if you want to keep the using 0.2.0.
Is there a specific reason that 0.2.0 release is needed?

**Comment by BowenD-UCB** [comment]
Thanks for clarify that. 
Since we have good backward compatibility, I think we don't need to fix this at the moment.
@janosh Can you please also take a look if the 0.2.0 release needs to be fixed?

**Comment by janosh** [comment]
i don't remember the details but we definitely had some hiccups in the v0.2.0 PyPI release when transitioning to the fast cythonized graph constructor which required making platform specific wheels for mac, win, linux instead of a simple source distribution.

that said, you _can't_ overwrite a previous pypi release. at most we could make a new release with the same version but higher build number (see [build tag docs](https://peps.python.org/pep-0427/#file-name-convention)) which is very rarely used but might fit our use case here.
i'm leaning more towards [just yanking the 0.2.0 release](https://pypi.org/help/#yanked) to discourage people from using it since it contains known bugs (#79).

**Comment by BowenD-UCB** [comment]
I agree with yanking the 0.2.0 version

**Comment by janosh** [comment]
@BowenD-UCB yanked [v0.2.0](https://pypi.org/project/chgnet/0.2.0/).
