### ISSUE TITLE
Calculating the energy of element Cs

### ISSUE THREAD

**Issue by Atefeh-Yadegarifard** [CederGroupHub/chgnet#55]
Hello. 
I would like to use CHGNet to calculate the energy of the element Cs. But when I use chgnet.predict_structure , I see an error like this: 
"graph_id=None has isolated atom with r_cutoff=5, should be skipped", stating that Cs is an isolated atom with atoms that are farther than 5 A from each other. I could not solve this problem with simply increasing the r_cutoff like this: CHGNet.r_cutoff = 10.0. So, I would like to ask for your assistance for solving this problem. Thank you and have a good day.

**Comment by BowenD-UCB** [comment]
Hi,

This is actually a known issue that is not supported by CHGNet.
The cutoff radius is a pre-set parameter that is used to construct pretrained CHGNet.
So, it can not be changed unless we train another CHGNet with setting r_cutoff = 6 at the beginning.

The inter-atomic distance in alkli metal Cs, like: https://next-gen.materialsproject.org/materials/mp-1?chemsys=Cs
is extremely long that exceeds 5A.
As Cs is an extreme case of super large inter-atomic distance, and almost no other system in Materials Project has similar issue, we had decided to keep 5A as the cut-off radius of CHGNet.
This is because increasing the cutoff radius of CHGNet will significantly increase its computation cost of CHGNet on all chemical systems.

If you're interested in studying Cs-related system. I will recommend you to initialize a new CHGNet with `atom_graph_cutoff = 6`, and train it on the Cs structures.

**Comment by BowenD-UCB** [comment]
this problem is addressed in https://github.com/CederGroupHub/chgnet/releases/tag/v0.3.0
