### ISSUE TITLE
parallel relaxation

### ISSUE THREAD

**Issue by bkmi** [CederGroupHub/chgnet#73]
Dear CHGNet Developers,

Is there capacity for the model to relax several crystal structures at once? It seems computations of energy, forces, and stress can easily be batched, but due to the dependence on the ASECalculator I don't see a trivial way to relax in parallel. Did I just miss it?

Thank you,
Ben

**Comment by BowenD-UCB** [comment]
The current parralel relaxation can be achieved with parallel GPU packages like RAY
read: https://docs.ray.io/en/latest/ray-core/tasks/using-ray-with-gpus.html

Or you can simply run submit multiple relaxation scripts.

While CHGNet naturally supports batched forward of multiple structures, batched-relxation is challenging due to:
1. There is no ASE support for this.
2.  It would require the relaxation to be synchronous, which is not likely with batched structures

**Comment by janosh** [comment]
Just to leave a note here that we welcome any external contributions that implement using CHGNet's multi-structure forward pass to draw from a pool of initial structures and relax them concurrently as previous structures finish.

![CHGNet Batch Relaxation](https://github.com/CederGroupHub/chgnet/assets/30958850/a658889f-3da8-4801-b2fc-e1f11a336507)
