### ISSUE TITLE
Energy jump when bond_graph_len becomes zero

### ISSUE THREAD

**Issue by PROA200** [CederGroupHub/chgnet#79]
### Version

0.2.1

### Which OS(es) are you using?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What happened?

When I compute the energy for a series of strained structures using CHGNet, I get a jump in the energy (and stress) when no edges remain in the bond graph (i.e., every pair of atoms is 3.0 A apart). This occurs silently, and I'm expecting the energy/stress to be smooth when the edges are broken. Am I missing something, or is there something wrong here?

### Code snippet

```python
import numpy as np
from pymatgen.core import Structure
from chgnet.model import CHGNet
import matplotlib.pyplot as plt

model = CHGNet.load()

distances = []
energies = []

struct = Structure(
    lattice=[
        [3.54216907, 0, 2.04507188],
        [1.18072406, 3.33958984, 2.04507188],
        [0, 0, 4.09014583],
    ],
    species=["Ag", "Br"],
    coords=[[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]],
)

for strain in np.linspace(0, 0.1, 20):
    struct_copy = struct.copy()
    struct_copy.apply_strain(strain)
    distances.append(struct_copy.distance_matrix[0][1])
    energies.append(model.predict_structure(struct_copy)["e"])

plt.plot(distances, energies, "o-")
plt.gca().set(xlabel="Distance (Å)", ylabel="Energy (eV)")
plt.show()
```

![gh-79](https://github.com/CederGroupHub/chgnet/assets/30958850/a09f3351-d4e7-4c55-8f05-69290b8ab11c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
Hi, 

Thanks a lot for reporting this issue, this is indeed a bug that leads to the concerning energy discontinuity in AgBr.

The energy jump becomes a serious issue in the AgBr structure because there exist a enormous sudden increase in the number of BondGraph edges at the discontinuity.
<img width="1014" alt="image" src="https://github.com/CederGroupHub/chgnet/assets/84425382/c577a9f0-518e-4484-93bc-0e923f357c17">

And we checked this issue is especially serious in AgBr composition, if we modify the composition the energy discontinuity is much smaller:
<img width="906" alt="image" src="https://github.com/CederGroupHub/chgnet/assets/84425382/ef51e9be-40de-4a57-baa0-bcaf53dcb63a">

We will fix this bug and retrain the model, this will be released in the next release

**Comment by janosh** [comment]
Closed by 1a558ea.

**Comment by BowenD-UCB** [comment]
An additional notes for users concerning about this issue:

The discontinuity in potential energy surface will only apear when a structure with zero bond graph, meaning there exists no single paired atoms within 3A, transfroms to a state with non-zero bond graph (at least one pair of atoms within 3A).

This is the case when we apply strain to AgBr structure.
In general, especially during a molecular dynamics, it is highly unlikely to have zero 3A paris, so that CHGNet version <= 0.2.1 should work with no problem for most use cases.

**Comment by BowenD-UCB** [comment]
This issue is now fully resolved: https://github.com/CederGroupHub/chgnet/releases/tag/v0.3.0
