### ISSUE TITLE
[How to run chgnet with initial charge]: 

### ISSUE THREAD

**Issue by mondalsou** [CederGroupHub/chgnet#83]
### Problem

I am trying to optimize the charged structure.  Is there any place to put the total charge inside the input? For example, If I want to calculate the total energy of the  [SO4]2-, how to put the total charge -2 to the input file ? I found one parameter called set_charge that is not working.

### Proposed Solution

WIll be good if we could set the total charge inside the input. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BowenD-UCB** [comment]
Hi,

Currently there is no way to add background charge in CHGNet calculation, if you're refering to something similar to VASP `NELECT`  setting.
This is definitely an interesting feature to add, but CHGNet is not capable of doing so since the training dataset of Materials Project consists of only charge neutral structures.

One possible workaround I can imagine now is to put the [SO4]2- in a charge neutral system (adding the cation), and take advantage of the site energy prediction of CHGNet to get the energy contribution from the [SO4]2-
